"""Added face_encodings in jsob format from webapp to database

Revision ID: 4698e2b1d4e7
Revises: e4074713cdec
Create Date: 2024-07-01 12:13:23.741735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4698e2b1d4e7'
down_revision = 'e4074713cdec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frs_db', schema=None) as batch_op:
        batch_op.alter_column('face_encoding',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frs_db', schema=None) as batch_op:
        batch_op.alter_column('face_encoding',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
