"""Added face_encodings in json format from webapp

Revision ID: 9799b73aa0d7
Revises: 9898c336e1d7
Create Date: 2024-07-01 12:55:51.114747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9799b73aa0d7'
down_revision = '9898c336e1d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frs_db', schema=None) as batch_op:
        batch_op.alter_column('face_encoding',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frs_db', schema=None) as batch_op:
        batch_op.alter_column('face_encoding',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)

    # ### end Alembic commands ###
